export enum ErrorDomain {
  E_CPF_INVALIDO = 'E_CPF_INVALIDO',
  E_NOME_OBRIGATORIO = 'E_NOME_OBRIGATORIO',
  E_ROLE_INVALID = 'E_ROLE_INVALID',
  E_EMAIL_INVALIDO = 'E_EMAIL_INVALIDO',
  E_EMAIL_MAX_CARACTERES = 'E_EMAIL_MAX_CARACTERES',
  E_NOME_MAX_CARACTERES = 'E_NOME_MAX_CARACTERES',
  E_AUTENTICACAO_INVALIDA = 'E_AUTENTICACAO_INVALIDA',
}