export enum ErrorDomain {
  E_CEP_INVALIDO = 'E_CEP_INVALIDO',
  E_TELEFONE_INVALIDO = 'E_TELEFONE_INVALIDO',
  E_CAMPO_OBRIGATORIO = 'E_CAMPO_OBRIGATORIO',
  E_FORMATO_INVALIDO = 'E_FORMATO_INVALIDO'
}